In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
sales = pd.read_parquet('../20260218_144523_sales_data.parquet', engine='pyarrow')
pd.options.display.max_rows = None
sales.head()

        date         category_name  item_id  sold_quantity  price  store_id
0 2025-04-01     Angebot Brötchen       139           15.0    0.0         0
1 2025-04-01  Angebot Feinbäckerei      138           28.0    0.0         0
2 2025-04-01  Angebot Heißgetränke      106           25.0    0.0         0
3 2025-04-01  Angebot Heißgetränke      539            5.0    1.4         0
4 2025-04-01         Angebot Snack      176            1.0    0.0         0

In [ ]:
##11
item_59 = (sales.item_id <= 59) & (sales.store_id == 6)
i59 = sales[item_59]

i59_df = pd.DataFrame(i59.groupby(['store_id', 'date','item_id', 'category_name' ])['item_id'].size())

display(i59_df.head(50))

                                           item_id
store_id date       item_id category_name
6        2025-04-01 0       Brötchen             1
                    1       Brötchen             1
                    2       Brötchen             1
                    5       Brötchen             1
                    6       Brötchen             1
                    7       Brötchen             1
                    8       Brötchen             1
                    10      Brötchen             1
                    11      Brötchen             1
                    12      Brötchen             1
                    18      Brötchen             1
                    21      Brötchen             1
                    23      Brötchen             1
                    24      Brötchen             1
                    25      Brötchen             1
                    26      Brötchen             1
                    27      Brötchen             1
                    28      Brötchen             1
                    30      Brötchen             1
                    31      Brötchen             1
                    32      Brötchen             1
                    33      Brötchen             1
                    34      Brötchen             1
                    37      Brötchen             1
                    39      Brötchen             1
                    40      Brötchen             1
                    41      Brötchen             1
                    43      Brötchen             1
                    49      Brötchen             1
                    50      Brötchen             1
                    51      Brot                 1
                    52      Brötchen             1
                    53      Brötchen             1
                    54      Brötchen             1
                    55      Brötchen             1
                    57      Brötchen             1
                    58      Brötchen             1
                    59      Brot                 1
                            Brötchen             1
         2025-04-02 0       Brötchen             1
                    1       Brötchen             1
                    2       Brötchen             1
                    5       Brötchen             1
                    6       Brötchen             1
                    7       Brötchen             1
                    8       Brötchen             1
                    10      Brötchen             1
                    11      Brötchen             1
                    12      Brötchen             1
                    18      Brötchen             1

In [ ]:
##!!

c = sales.groupby(['category_name'])['item_id'].value_counts(normalize=False,)
pd.DataFrame(c).sort_

values('count', ascending=True)

                              count
category_name        item_id
Snack                509          1
                     560          1
Snack Belag          437          1
Printen/Kekse        365          1
                     128          1
                     364          1
                     359          1
                     363          1
Kuchen               210          1
                     238          1
                     271          1
                     672          1
                     226          1
Angebot Snack        486          1
                     483          1
                     485          1
Printen Waage        299          1
Kaltgetränke 19%     636          1
Konditorei           419          1
                     399          1
                     221          1
                     407          1
                     425          1
                     415          1
                     413          1
                     69           1
                     416          1
                     392          1
                     389          1
                     417          1
                     393          1
                     211          1
Heißgetränke         664          1
Frühstücke           594          1
                     591          1
Brötchen             38           1
Gastro Gerichte      580          1
Brötchen             178          1
                     184          1
                     17           1
                     76           1
                     51           1
Angebot Feinbäckerei 45           1
Angebot Brötchen     99           1
                     28           1
Snack                510          1
Angebot Gastro       155          1
Brötchen             194          1
Frühstücke           596          1
Snack                460          1
Brot                 78           1
Brotwaage            87           1
Brot                 324          1
Gastro Gerichte      592          1
Feinbäckerei         301          1
Snack                505          1
                     448          1
Brot                 91           1
                     331          1
                     81           1
Konditorei           395          2
Printen/Kekse        126          2
Snack Belag          500          2
Printen/Kekse        131          2
Brot                 77           2
                     327          2
                     92           2
Snack                508          2
Gastro Gerichte      172          2
Kuchen               153          2
                     264          2
                     298          2
Heißgetränke         544          2
Konditorei           258          2
                     403          2
Brötchen             181          2
                     15           2
                     36           2
Angebot Heißgetränke 105          2
Brötchen             166          2
Konditorei           397          3
Frühstücke           593          3
Gastro Gerichte      669          3
Angebot Snack        482          3
Printen/Kekse        370          3
Kuchen               284          3
Konditorei           409          4
Frühstücke           450          4
Gastro Gerichte      670          4
Konditorei           396          4
                     414          4
Angebot Snack        478          4
Snack                504          4
Angebot Feinbäckerei 156          4
                     305          4
Konditorei           423          4
Printen/Kekse        361          4
Konditorei           398          4
                     420          4
                     401          4
Printen/Kekse        367          4
Brötchen             111          5
Feinbäckerei         295          5
Gastro Gerichte      668          5
Brötchen             200          5
Angebot Snack        157          5
Printen/Kekse        371          5
Konditorei           384          5
                     390          5
Kuchen               244          5
Snack                427          5
                     507          5
Printen/Kekse        369          5
Konditorei           421          6
Angebot Snack        481          6
Kuchen               266          6
Konditorei           382          6
Snack                506          6
Angebot Snack        476          6
Konditorei           385          7
Frühstücke           466          7
Konditorei           394          7
Brötchen             177          7
                     171          7
Konditorei           412          7
                     418          7
Printen/Kekse        133          8
                     362          8
Konditorei           391          8
                     424          9
Brötchen             201          9
Kuchen               216         10
                     353         10
Printen/Kekse        350         10
Brötchen             255         10
Konditorei           422         11
Brötchen             113         11
                     170         11
Feinbäckerei         204         12
Brot                 318         12
Gastro Gerichte      587         12
Angebot Feinbäckerei 143         12
Frühstücke           451         12
Heißgetränke         663         12
Brötchen             75          12
Gastro Gerichte      590         12
Printen/Kekse        374         13
Kaltgetränke 19%     676         13
Heißgetränke         512         13
Konditorei           383         13
                     402         13
Angebot Snack        477         13
Brot                 108         13
Brötchen             168         14
Gastro Gerichte      584         14
                     581         14
Brötchen             72          14
Snack                463         15
Brötchen             149         15
Gastro Gerichte      589         16
Angebot Snack        479         16
Kuchen               243         16
Konditorei           405         16
                     406         16
Heißgetränke         662         16
Angebot Brötchen     151         17
Brot                 330         17
Konditorei           387         17
Gastro Gerichte      588         18
Brötchen             73          18
Gastro Gerichte      583         18
Heißgetränke         540         19
Gastro Gerichte      578         19
Kaltgetränke 19%     599         19
Gastro Gerichte      585         20
Brötchen             112         20
Gastro Gerichte      582         20
                     586         20
Heißgetränke         632         20
Gastro Gerichte      167         20
Brötchen             169         21
Angebot Brot         473         22
Snack Belag          579         23
Angebot Snack        480         23
Konditorei           404         24
Snack Belag          454         25
Konditorei           388         26
Angebot Heißgetränke 148         26
Heißgetränke         532         26
Snack                498         28
Angebot Snack        475         29
Heißgetränke         661         29
Kaltgetränke 7%      606         29
Angebot Heißgetränke 47          29
Heißgetränke         630         30
Snack                558         31
Kuchen               307         32
Angebot Heißgetränke 177         33
Angebot Brötchen     146         35
Brot                 345         35
Frühstücke           452         35
Snack                444         37
Heißgetränke         534         38
Snack                489         38
Angebot Heißgetränke 147         38
Feinbäckerei         290         39
Brot                 100         39
Angebot Snack        469         40
                     472         41
Kuchen               237         41
Heißgetränke         531         41
Kuchen               275         42
Printen/Kekse        115         43
Printen Waage        355         43
Konditorei           408         43
Kuchen               219         45
Snack                553         45
Snack Belag          494         46
Brötchen             42          46
Gastro Gerichte      577         46
                     574         47
Frühstücke           595         49
Kuchen               276         50
Gastro Gerichte      573         51
                     576         53
Printen Waage        373         54
Kuchen               294         55
Gastro Gerichte      575         55
                     314         55
                     459         56
Snack                550         56
Angebot Brötchen     467         56
Gastro Gerichte      311         57
Konditorei           400         57
Gastro Gerichte      457         57
                     312         57
Angebot Snack        474         58
Snack                438         58
Feinbäckerei         137         58
Gastro Gerichte      455         58
Feinbäckerei         225         58
                     205         58
Kuchen               236         59
Heißgetränke         635         59
Gastro Gerichte      456         59
                     458         59
Heißgetränke         533         59
Brötchen             172         61
                     35          61
Angebot Brot         470         62
Snack Belag          464         62
                     597         63
Angebot Brot         468         65
Angebot Kuchen       471         65
Heißgetränke         530         70
Kaltgetränke 19%     608         70
Konditorei           411         71
Brot                 310         72
Angebot Brötchen     145         73
Brot                 323         73
                     325         74
Kaltgetränke 19%     645         76
Brötchen             16          77
Angebot Brot         178         77
Snack                443         77
Snack Belag          430         77
Kaltgetränke 19%     541         79
Konditorei           268         81
Angebot Brötchen     152         81
Eigerichte           571         83
Angebot Brötchen     154         83
Heißgetränke         525         83
Printen/Kekse        119         84
                     376         86
Heißgetränke         538         90
                     528         90
                     526         91
Brot                 162         91
                     381         91
                     558         91
Kuchen               352         91
Brot                 557         91
Heißgetränke         527         93
                     529         93
Printen/Kekse        358         94
                     377        100
Feinbäckerei         265        103
Konditorei           410        104
Heißgetränke         665        104
                     627        106
Snack                488        112
Printen/Kekse        135        112
Snack                549        113
Feinbäckerei         22         116
Heißgetränke         629        118
Konditorei           212        119
Brot                 511        122
Brötchen             202        122
Kuchen               135        123
Angebot Brötchen     144        131
Brötchen             89         134
Printen/Kekse        379        139
Feinbäckerei         288        142
Angebot Snack        176        143
Kuchen               349        143
Brötchen             175        147
Printen/Kekse        354        149
Konditorei           386        153
Feinbäckerei         230        155
Heißgetränke         631        165
Printen/Kekse        132        167
Brötchen             124        167
Printen/Kekse        127        167
Snack Belag          497        173
                     495        178
Heißgetränke         537        180
Kaltgetränke 19%     607        181
Brötchen             222        182
                     224        182
Brot                 380        182
                     491        182
Brötchen             186        182
Brot                 490        182
Kuchen               351        182
Brot                 497        182
                     502        182
                     556        182
                     494        182
                     555        182
                     545        182
Brötchen             187        182
Snack Belag          440        185
Konditorei           233        185
Brot                 335        186
Snack Belag          439        187
Printen/Kekse        366        195
Kuchen               118        195
Feinbäckerei         120        196
Brot                 329        202
Heißgetränke         628        204
                     626        212
Brötchen             254        215
Kaltgetränke 7%      616        221
Eigerichte           496        223
Brot                 375        226
Brötchen             84         229
                     90         230
Snack                502        232
Brot                 347        234
                     334        236
                     61         238
                     346        239
Snack Belag          666        241
Konditorei           256        243
Heißgetränke         625        248
Printen/Kekse        129        250
Snack Belag          493        253
Printen/Kekse        357        255
Angebot Brötchen     44         255
Feinbäckerei         289        260
Eigerichte           565        264
Konditorei           208        279
Angebot Snack        484        280
Angebot Heißgetränke 539        280
Angebot Brötchen     179        283
Feinbäckerei         282        297
Heißgetränke         514        303
Printen/Kekse        378        304
Eigerichte           566        304
Snack Belag          436        314
Brot                 65         322
Kuchen               274        323
Feinbäckerei         229        323
Kuchen               217        323
Brötchen             165        327
Konditorei           297        331
Eigerichte           567        333
Printen/Kekse        368        334
Kaltgetränke 19%     657        336
                     658        336
Kuchen               304        340
Konditorei           218        342
                     380        344
Kaltgetränke 19%     643        344
                     659        345
                     660        353
Brötchen             196        356
                     197        356
                     198        356
                     199        357
Kaltgetränke 19%     656        368
Snack                551        369
Snack Belag          543        372
Brot                 97         377
Brötchen             125        383
Printen/Kekse        372        385
Feinbäckerei         223        386
Konditorei           259        392
Brot                 326        396
Kuchen               228        400
Konditorei           239        400
Kuchen               207        411
Snack Belag          632        411
Konditorei           257        414
Kaltgetränke 19%     640        415
Printen/Kekse        360        418
Heißgetränke         536        419
Brot                 315        425
Printen/Kekse        356        432
Brot                 321        436
Feinbäckerei         277        438
Brot                 314        439
Kaltgetränke 19%     639        440
Snack                570        447
                     546        449
                     552        455
Brot                 332        460
Snack                497        475
Kaltgetränke 19%     642        476
Eigerichte           564        479
                     562        483
Konditorei           241        484
Feinbäckerei         303        493
Brötchen             249        505
Brot                 83         510
Snack                499        515
Eigerichte           563        515
Heißgetränke         521        517
Snack Belag          492        518
Brot                 320        519
Snack                501        530
                     503        535
Feinbäckerei         302        536
Snack                547        541
                     548        542
                     559        545
                     554        557
Eigerichte           561        557
Kuchen               296        561
Snack                487        569
Printen/Kekse        130        569
Brot                 66         591
Heißgetränke         535        597
Kuchen               110        599
Brot                 319        604
Brötchen             114        610
                     164        610
                     173        612
                     163        612
                     159        613
Konditorei           381        621
Kaltgetränke 19%     609        626
Brötchen             251        632
                     253        636
Brot                 313        642
Brötchen             180        643
                     250        644
Brot                 309        647
Brötchen             252        647
                     256        647
                     162        648
Brot                 308        648
Brötchen             161        648
                     248        648
                     174        648
                     167        648
Brot                 316        648
                     312        648
                     322        648
                     317        648
                     348        649
Snack Belag          630        649
Brot                 116        657
Brötchen             160        665
Printen/Kekse        134        726
Angebot Feinbäckerei 278        731
Kaltgetränke 19%     613        747
Angebot Brot         158        748
Angebot Brötchen     168        760
Kuchen               283        767
                     287        768
Brötchen             123        770
                     126        772
                     121        774
                     24         777
                     27         778
                     122        779
                     28         781
Feinbäckerei         292        797
Kuchen               209        804
Angebot Brötchen     624        813
Brötchen             30         818
Konditorei           291        835
Brot                 80         835
Konditorei           250        851
Brot                 85         857
Kuchen               140        859
Konditorei           234        861
Snack Belag          667        876
Brötchen             53         882
Angebot Feinbäckerei 673        898
Heißgetränke         516        920
Brot                 63         930
Kuchen               306        950
Brot                 58         955
Brötchen             52         964
                     55         965
                     57         968
                     49         968
                     50         968
                     54         968
                     59         968
                     58         968
Kuchen               273        992
                     214       1006
Brot                 56        1009
Kuchen               245       1023
Snack Belag          442       1023
Brot                 82        1028
Snack Belag          604       1040
Brot                 64        1073
Heißgetränke         522       1075
Feinbäckerei         293       1098
Kuchen               231       1098
Snack Belag          671       1134
                     462       1136
Heißgetränke         542       1144
Kaltgetränke 19%     654       1145
Kuchen               240       1146
Angebot Brötchen     170       1148
Kaltgetränke 19%     614       1149
Kuchen               142       1187
                     242       1202
Kaltgetränke 19%     612       1204
                     611       1210
Feinbäckerei         29        1213
Snack                445       1217
                     453       1220
Brot                 62        1230
                     52        1236
Kuchen               215       1237
Brötchen             3         1271
Kaltgetränke 19%     655       1271
Brötchen             4         1277
Snack Belag          634       1299
Heißgetränke         620       1314
Brötchen             14        1344
Feinbäckerei         117       1357
Snack                572       1359
Brot                 337       1361
Snack Belag          441       1372
Konditorei           206       1384
Kaltgetränke 19%     615       1399

:

In [ ]:
##!!
sales.plot(x='item_id' , figsize=(15,5), kind='bar', colormap='magma' )
plt.grid(axis='y', alpha=0.6)    
plt.show()

KeyboardInterrupt:

In [8]:
b = sales.query('sold_quantity == 0')
b.head(20)

          date category_name  item_id  sold_quantity  price  store_id
10  2025-04-01          Brot       70            0.0   2.90         0
11  2025-04-01          Brot       71            0.0   3.80         0
17  2025-04-01          Brot       88            0.0   5.40         0
28  2025-04-01          Brot      315            0.0    NaN         0
39  2025-04-01          Brot      338            0.0    NaN         0
41  2025-04-01          Brot      340            0.0    NaN         0
43  2025-04-01          Brot      342            0.0    NaN         0
46  2025-04-01          Brot      375            0.0   3.80         0
48  2025-04-01      Brötchen        1            0.0   0.52         0
50  2025-04-01      Brötchen        5            0.0   0.95         0
51  2025-04-01      Brötchen        6            0.0   1.10         0
52  2025-04-01      Brötchen        7            0.0   1.50         0
53  2025-04-01      Brötchen        8            0.0   0.62         0
70  2025-04-01      Brötchen       37            0.0   0.90         0
77  2025-04-01      Brötchen       52            0.0    NaN         0
78  2025-04-01      Brötchen       54            0.0    NaN         0
79  2025-04-01      Brötchen       55            0.0    NaN         0
82  2025-04-01      Brötchen       59            0.0   1.65         0
86  2025-04-01      Brötchen      125            0.0   1.00         0
108 2025-04-01      Brötchen      248            0.0    NaN         0

In [18]:
l = ['s1', 's2', 's3', 's4', 's', '5', ' ']

for i in l:
    print(i.isalnum())

True
True
True
True
True
True
False